services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules # Keep node_modules excluded
    env_file:
      - .env # Load environment variables from .env file
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:
